---
# roles/cluster_health/defaults/main.yml

# Ruta al ejecutable de kubectl y kubeconfig de RKE2
rke2_kubectl_path: "/var/lib/rancher/rke2/bin/kubectl"
rke2_kubeconfig_path: "/etc/rancher/rke2/rke2.yaml"

# Destino del reporte en el nodo master
cluster_health_report_dest: "/tmp/cluster_health_report.html"

# Destino local del reporte en la máquina donde se ejecuta Ansible
cluster_health_local_report_dest: "{{ playbook_dir }}/reports/cluster_health_report.html"

# Ventana de tiempo (en horas) para buscar eventos de advertencia
cluster_health_events_time_window: "2h"
