---
# inventories/production/hosts.yml
all:
  children:
    # Nodos Master de Kubernetes donde reside etcd
    control_planes:
      hosts:
        k8s-master-01.infra.local:
          ansible_host: 192.168.10.11
        k8s-master-02.infra.local:
          ansible_host: 192.168.10.12
        k8s-master-03.infra.local:
          ansible_host: 192.168.10.13

    # Servidores de destino donde se depositarán los backups
    backup_servers:
      hosts:
        backup-storage-01.infra.local:
          ansible_host: 192.168.20.50
        backup-storage-02.infra.local:
          ansible_host: 192.168.20.51
