---
# roles/etcd_backup/tasks/schedule.yml

- name: Instalar el script de backup en /usr/local/bin
  ansible.builtin.template:
    src: etcd-backup-script.sh.j2
    dest: /usr/local/bin/etcd-backup.sh
    mode: '0750'
    owner: root
    group: root

- name: Instalar el servicio de Systemd para backup de etcd
  ansible.builtin.template:
    src: etcd-backup.service.j2
    dest: /etc/systemd/system/etcd-backup.service
    mode: '0644'
    owner: root
    group: root
  register: systemd_service_update

- name: Instalar el temporizador (Timer) de Systemd
  ansible.builtin.template:
    src: etcd-backup.timer.j2
    dest: /etc/systemd/system/etcd-backup.timer
    mode: '0644'
    owner: root
    group: root
  register: systemd_timer_update

- name: Recargar el demonio systemd si hubo cambios en los archivos
  ansible.builtin.systemd:
    daemon_reload: true
  when: systemd_service_update.changed or systemd_timer_update.changed

- name: Habilitar e iniciar el timer de systemd para backup periódico
  ansible.builtin.systemd:
    name: etcd-backup.timer
    state: started
    enabled: true

- name: Validar estado del timer de systemd
  ansible.builtin.command: systemctl status etcd-backup.timer
  changed_when: false
  register: timer_status

- name: Mostrar estado actual de la programación
  ansible.builtin.debug:
    var: timer_status.stdout_lines
